### ISSUE TITLE
cart-item.component.ng-problem.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [RomanKhomenko/angular5-cdp#5]
Директива ngModel находиться в модуле FormsModule.
Я не вижу, чтобы где-то этот модуль был подключен.
Добавьте d products-feature.module.ts 
import { FormsModule } from '@angular/forms';
imports: [CommonModule, SharedModule, FormsModule],
и все заработает.

**Comment by RomanKhomenko** [comment]
Everything is clear. Thank you!
