### ISSUE TITLE
product-list.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [RomanKhomenko/angular5-cdp#6]
Не понял предназначение вот этой функции
resolveFn: Function|null = null;

**Comment by RomanKhomenko** [comment]
это единственный способ найденный мной, чтобы использовать промайсы и async pipe вместе.
В моей первом варианте использования, было так:
`getProducts() {
    this.productService.getProducts()
      .then(resp => new Promise(...)
  }`
Это порождало новый промайс - async pipe срабатывал и ничего не работало. [issue](https://github.com/angular/angular/issues/6696)
Собственно решение не создавать каждый раз новый промайс, а резолвать существующий. поэтому и нужна ссылка на функцию резолвер. Взял с сайта доков ангуляра. [see example](https://angular.io/api/common/AsyncPipe)
